// <auto-generated />
namespace Assessment1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addingvintovehiclemodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingvintovehiclemodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201806211348483_adding vin to vehicle model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
